---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
# Please put your title here to include it in the file below.
Title <- "Title of your paper goes here"
```

# pcreg: Principal Component Regression analysis for tree ring data

## Motivation

## How to Cite

## Installation

The most up-to-date version can be installed from the GitHub repository using the `remotes` package. It can also be accomplished with the `devtools` package but devtools got a bit bloated and the components were split into individual packages. `remotes` is more streamlined if not engaging in lots of full package development and just wanting to install packages from online sources besides CRAN.

```
# install.packages("remotes")
library(remotes)
remotes::install_github("https://github.com/lgsmith295/pcreg")
```

## Versioning

## How to Use

## Licenses

See the [DESCRIPTION](DESCRIPTION) and [LICENSE](LICENSE) files.

## Contributions

We welcome contributions from everyone. Before you get started, please see our [contributor guidelines](CONTRIBUTING.md). Please note that this project is released with a [Contributor Code of Conduct](CONDUCT.md). By participating in this project you agree to abide by its terms.

## Acknowledgements

## References

